### ISSUE TITLE
Check ghost layers

### ISSUE THREAD

**Issue by Gustry** [3liz/QgisLayerBoardPlugin#22]
Do they still exist in QGIS 3?
Do they exist only in QGIS 2 project?

For now, it's always `False` in the plugin

**Comment by rldhont** [comment]
I don't know if QGIS 3 still produces Ghost layers but it does not destroyed them if they exist.

**Comment by rldhont** [comment]
The **shadow** layers still exists in 3.4.*

During a training session, with PostgreSQL/PostGIS layers, QGIS does not well removed layer from map layers project registry.

**Comment by Gustry** [comment]
I tried to replicate the issue.

* Create a new project with 3.4.12
* Add some PostGIS layers
* Check the content of the QGS file
* Remove one/some/all PostGIS layers
* Check the content of the QGS file, it didn't notice something wrong.

At the end, my QGS file was nearly empty without reference to a layer.

I still don't have ghost layers. Maybe I'm doing the correct steps.

**Comment by rldhont** [comment]
It is more like this:
* Create PostGIS a connexion without option metadata
* Add a layer
* Upate the connexion to check metadata
* Remove the layer
* Add the removed layer
The layer removed and then added is twice in the map layers list and once in layer tree.

**Comment by Gustry** [comment]
From @rldhont on a chat:
> <reluc> en fait si tu regardais QgsProject.instance.mapLayers().keys()
<reluc> tu voyais au moins 2 couches avec le même début pour l'id
<reluc> donc 2 fois la même couche

**Comment by Gustry** [comment]
@rldhont @mdouchin Please check the latest version, it should be fixed.
It has been released on qgis.org.
