### ISSUE TITLE
Warning: changing datasource crash Qgis

### ISSUE THREAD

**Issue by enricofer** [3liz/QgisLayerBoardPlugin#6]
Hi Michel, 
I see that you realeased the new version of plugin without apply the patch I provide you (https://github.com/3liz/QgisLayerBoardPlugin/pull/5).
This is very annoying because the inversion of two variables crashes Qgis!!! Please consider apply the fix and re-submit the plugin

Regards.
Enrico.

**Comment by mdouchin** [comment]
Arg, sorry for this !
I will release a version 0.3.1 today

**Comment by mdouchin** [comment]
done in 0.4
